blank_issues_enabled: false
contact_links:
  - name: Features, Bug Reports, Questions
    url: https://discord.gg/5GhK7E54yA
    about: Our preferred starting point if you have any questions or suggestions
